sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t serhii/docker-react-course -f Dockerfile.dev .

script:
  - docker run -e CI=true serhii/docker-react-course npm run test
